config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  get 'about' => 'about#index'
  get 'policies/terms_of_service'
  get 'policies/privacy'
  get 'policies/cookies' => 'policies#cookies_terms'
  get 'support/faq' => 'support#faq'
  get 'support/rules' => 'support#rules'
  get 'support/contact' => 'support#contact'
  post 'support/contact' => 'support#contact'
  get 'press' => 'press#index'

  get 'login' => 'users#login'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#delete'

  get 'signup' => 'users#new'
  get 'confirm_account' => 'users#confirm_account'
  post 'confirm_account' => 'users#validate_confirm_account'

  get 'recovery_password' => 'recovery_password#index'
  match 'recovery_password/confirm_code' => 'recovery_password#confirm_code', via: [:get, :post]
  match 'recovery_password/confirm_new_password' => 'recovery_password#confirm_new_password', via: [:get, :post]
  post 'recovery_password/set_new_password' => 'recovery_password#set_new_password'

  resources :users

  patch 'products/:id/disable' => 'products#disable', as: :disable_product
  patch 'products/:id/enable' => 'products#enable', as: :enable_product
  resources :products

  match 'cart' => 'cart#index', via: [:get, :post]
  post '/cart/add' => 'cart#add'

  get 'settings', to: 'settings#edit', as: :settings
  get 'settings', to: 'settings#edit', as: :setting
  get 'settings', to: 'settings#update'
  get 'settings/show', to: 'settings#show'
  get 'settings/disable_account' => 'settings#disable_account'
  match 'settings/disable_account/confirmation' => 'settings#disable_account_confirmation', via: [:get, :post], as: 'settings_disable_account_confirmation'
  get 'settings/disable_account/confirmed' => 'settings#disable_account_confirmed'

end

app/models/user.rb
class User < ActiveRecord::Base
  USERNAME_MINIMUM_LENGTH = 3
  USERNAME_MAXIMUM_LENGTH = 15
  USERNAME_VALID_FORMAT_PATTERN = /\A\w+\z/
  PASSWORD_MINIMUM_LENGTH = 6
  EMAIL_VALID_FORMAT_PATTERN = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  has_one :setting

  validates :username,
    length: {
      minimum: USERNAME_MINIMUM_LENGTH,
      maximum: USERNAME_MAXIMUM_LENGTH,
    },
    format: {
      with: USERNAME_VALID_FORMAT_PATTERN,
      message: 'Username must content only alphanumeric and underscore characters.'
    }

  validates :username,
    uniqueness: true,
    on: :create

  validates :password,
    presence: true,
    length: {
      minimum: PASSWORD_MINIMUM_LENGTH
    },
    on: :create

    validates :password,
      presence: true,
      length: {
        minimum: PASSWORD_MINIMUM_LENGTH
      },
      allow_blank: true,
      on: :update


  validates :email,
     format: {
       with: EMAIL_VALID_FORMAT_PATTERN,
       message: 'Email must be have a valid email.'
     }

  validates :email,
     uniqueness: true,
     on: :create

  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if ! is_user_logged? || session[:user][:id] != @user.id
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      @user.confirmation_code = SecureRandom.uuid
      @user.username.downcase!
      if @user.save
        userSetting = Setting.new({user_id: @user.id})
        if userSetting.save!
          UserMailer.confirmationEmail(@user).deliver_now
          format.html { redirect_to confirm_account_path, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: userSetting.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if is_user_logged? && session[:user][:id] == @user.id
        if uploaded_picture?
          uploaded_picture = params.require(:user)[:uploaded_picture]
          move_uploaded_pictured_into_default_path uploaded_picture
          @user.avatar_path = '/images/users/avatars/' + uploaded_picture.original_filename
        end
        if ! username_modified? && ! email_modified? && can_the_administrator_field_to_be_update? && @user.save
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          if username_modified?
            @user.errors.add(:username, 'can not be changed')
          end
          if email_modified?
            @user.errors.add(:email, 'can not be changed')
          end
          if ! can_the_administrator_field_to_be_update?
            @user.errors.add(:is_administrator, 'You have not permission')
          end
          format.html { render :edit, notice: 'Upss. ' + @user.errors.full_messages.inject {|errors, error| errors + error} }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      else
        format.html { render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false) }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    respond_to do |format|
      format.html { render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false) }
      format.json { head :no_content }
    end
  end

  # GET /confirm_account
  def confirm_account
    @user = User.new
    if params.has_key?(:confirmation_code)
      @user.confirmation_code = params[:confirmation_code]
    end
  end

  # POST /confirm_account
  def validate_confirm_account
    respond_to do |format|
      if params[:user].present? && params[:user][:confirmation_code].present?
        @user = User.find_by confirmation_code: params[:user][:confirmation_code]
        if @user
            @user.confirmation_code = nil
            if @user.save(validate: false)
              format.html { redirect_to login_path, notice: 'Account was successfully validated! Please login with your data.' }
              format.json { render :show, status: :ok, location: @user }
            else
              @user.errors.add(:confirmation_code, 'has not been validated. Please try again.')
              format.html { render :confirm_account }
              format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        else
          @user = User.new
          @user.errors.add(:confirmation_code, 'not found.')
          format.html { render :confirm_account }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      else
        @user = User.new
        @user.errors.add(:confirmation_code, 'is empty.')
        format.html { render :confirm_account }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /login
  def login
    @user = User.new
    if is_user_logged?
      redirect_to user_path({:id => session[:user]['id']})
    else
      @username_or_email = (session.has_key? (:username_or_email)) ? session[:username_or_email] : ''
      session.delete(:username_or_email)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :is_administrator, :uploaded_picture)
    end

    def username_modified?
      @user.username != user_params[:username]
    end

    def email_modified?
      ! user_params[:email].nil? && @user.email != user_params[:email]
    end

    def is_administrator_modified?
      ! user_params[:is_administrator].nil? && user_params[:is_administrator] != @user.is_administrator
    end

    def can_the_administrator_field_to_be_update?
      ! is_administrator_modified? || is_administrator_modified? && @user.is_administrator
    end

    def uploaded_picture?
      params.required(:user).has_key?(:uploaded_picture)
    end

    def move_uploaded_pictured_into_default_path uploaded_picture
      File.open(
        Rails.root.join('public', 'images', 'users', 'avatars', uploaded_picture.original_filename),
        'wb'
      ) do |file|
        file.write(uploaded_picture.read)
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
  USERNAME_VALID_FORMAT_NOT_REGISTERED = 'imnotregistered'
  EMAIL_VALID_FORMAT_NOT_REGISTERED = 'thisemailsisnotregistered@themonkeyisland.com'
  PASSWORD_VALID_FORMAT_STANDARD_FOR_ALL_USERS = 'secret'
  PASSWORD_VALID_FORMAT_WRONG = 'wrong'
  PASSWORD_VALID_FORMAT_STANDARD_FOR_UPDATE = 'new_password'
end

app/views/users/_confirm_account_form.erb
<%= form_for(@user, url: {action: 'confirm_account'}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :confirmation_code %><br>
    <%= f.text_field :confirmation_code %>
  </div>

  <div class="actions">
    <%= f.submit "Confirm account" %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, html: {multipart: true}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :username %><br>
    <% if @user.new_record? %>
      <%= f.text_field :username %>
    <% else %>
      <%= f.text_field :username, readonly: 'readonly' %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <% if @user.new_record? %>
      <%= f.text_field :email %>
    <% else %>
      <%= f.text_field :email, readonly: 'readonly' %>
    <% end %>

  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <% if @user.is_administrator %>
    <div class="field">
      <%= f.label :is_administrator %><br>
      <%= f.check_box :is_administrator %>
    </div>
  <% end %>
  <% if ! @user.new_record? %>
    <div class="field">
      <%= f.label :avatar_path %><br>
      <%
        if @user.avatar_path.nil?
          concat image_tag 'users/default_avatar.png'
        else
          concat image_tag @user.avatar_path
        end
       %>
       <br>
       Upload picture: <%= f.file_field("uploaded_picture") %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_login_form.erb
<%= form_tag( login_path, method: 'post') do %>
  <div class="field">    
    <%= label_tag 'Username or password' %><br>
    <%= text_field_tag 'session[username_or_email]', username_or_email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br>
    <%= password_field_tag 'session[password]' %>
  </div>
  <p><a href="<%= recovery_password_path %>">forget your password?</a></p>
  <div class="actions">
    <%= submit_tag "log in" %>
  </div>
<% end %>

app/views/users/confirm_account.erb
<h1>Confirm account</h1>
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>
<%= render 'confirm_account_form' %>

<%= #link_to 'Back', root_path
%>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
        <%
          if user.avatar_path.nil?
            concat image_tag 'users/default_avatar.png', width: 100
          else
            concat image_tag user.avatar_path, width: 100
          end
        %>
        </td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%
          if session.has_key?(:user) && session[:user][:id] == user.id
            concat link_to'Edit', edit_user_path(user)
          end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/login.erb
<h1>Login</h1>
<p id="notice"><%= (notice.nil?)? '' : notice.html_safe %></p>
<%= render 'login_form', username_or_email:   @username_or_email %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%
  if @user.avatar_path.nil?
    concat image_tag 'users/default_avatar.png'
  else
    concat image_tag @user.avatar_path
  end
%>
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<% if session.has_key?(:user) && session[:user][:is_administrator] %>
<p>
  <strong>Is administrator:</strong>
  <%
      concat check_box_tag :is_administrator, '1', @user.is_administrator
  %>
</p>
<% end %>

<%
  if session.has_key?(:user) && session[:user][:id] == @user.id
    concat link_to('Edit', edit_user_path(@user)) + ' | '
  end
%>
<%= link_to 'Back', users_path %>