config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  get 'about' => 'about#index'
  get 'policies/terms_of_service'
  get 'policies/privacy'
  get 'policies/cookies' => 'policies#cookies_terms'
  get 'support/faq' => 'support#faq'
  get 'support/rules' => 'support#rules'
  get 'support/contact' => 'support#contact'
  post 'support/contact' => 'support#contact'
  get 'press' => 'press#index'

  get 'login' => 'users#login'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#delete'

  get 'signup' => 'users#new'
  get 'confirm_account' => 'users#confirm_account'
  post 'confirm_account' => 'users#validate_confirm_account'

  get 'recovery_password' => 'recovery_password#index'
  match 'recovery_password/confirm_code' => 'recovery_password#confirm_code', via: [:get, :post]
  match 'recovery_password/confirm_new_password' => 'recovery_password#confirm_new_password', via: [:get, :post]
  post 'recovery_password/set_new_password' => 'recovery_password#set_new_password'

  resources :users

  patch 'products/:id/disable' => 'products#disable', as: :disable_product
  patch 'products/:id/enable' => 'products#enable', as: :enable_product
  resources :products

  match 'cart' => 'cart#index', via: [:get, :post]
  post '/cart/add' => 'cart#add'

  get 'settings', to: 'settings#edit', as: :settings
  get 'settings', to: 'settings#edit', as: :setting
  get 'settings', to: 'settings#update'
  get 'settings/show', to: 'settings#show'
  get 'settings/disable_account' => 'settings#disable_account'
  match 'settings/disable_account/confirmation' => 'settings#disable_account_confirmation', via: [:get, :post], as: 'settings_disable_account_confirmation'
  get 'settings/disable_account/confirmed' => 'settings#disable_account_confirmed'

end

app/models/setting.rb
class Setting < ActiveRecord::Base
  belongs_to :user
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :user_must_be_logged
  before_action :set_setting, only: [:show, :edit, :update, :destroy, :disable_account_confirmation]


  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def disable_account
  end

  def disable_account_confirmation
    if is_confirmation_code_coming?
      if is_confirmation_code_void?
        flash.now[:alert] = 'Confirmation code is void. Please, review your email and verify your confirmation code.'
      elsif ! is_confirmation_code_valid?
        flash.now[:alert] = 'Confirmation code not found. Please, review your email and verify your confirmation code.'
      else
        disable_user_account
        if @setting.user.save

          redirect_to settings_disable_account_confirmed_url
        else
          flash.now[:alert] = 'Account has could be disabled.'
        end
      end
    else
      @setting.confirmation_code = SecureRandom.uuid
      @setting.save
      UserMailer.disableYourAccount(User.find_by(id: get_logged_user_identifier), @setting).deliver_now
    end
  end

  def disable_user_account
    @setting.user.is_account_enable = false
  end

  def disable_account_confirmed
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find_by(user_id: session[:user][:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.fetch(:settings, {}).permit(:confirmation_code)
    end

    def is_confirmation_code_void?
      setting_params[:confirmation_code] == ''
    end

    def is_confirmation_code_valid?
      @setting.confirmation_code == setting_params[:confirmation_code]
    end

    def is_confirmation_code_coming?
      ! setting_params.nil? && ! setting_params[:confirmation_code].nil?
    end
end

app/helpers/settings_helper.rb
module SettingsHelper

  def get_url_for_disable_account_link confirmation_code
    settings_disable_account_confirmation_url + '?confirmation_code=' + confirmation_code.to_s
  end
end

app/views/settings/_form.html.erb
<%= form_for(@setting) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
  <hr/>
  <a href="<%= settings_disable_account_path %>">Disable my account</a>
<% end %>

app/views/settings/disable_account.erb
<h1>Disable my account</h1>
<p>Are you sure?</p>
<p><%= link_to 'back', settings_path %> <%= link_to 'disable', settings_disable_account_confirmation_path %></p>

app/views/settings/disable_account_confirm.erb
<h1>Disable your account</h1>
<%= form_tag({}, {name: 'disable_account_confirm'}) do %>
  <p>Confirmation code</p>
  <p><%= text_field_tag 'confirmation_code', nil, placeholder: "Enter your confirmation code" %></p>
  <p><%= submit_tag 'disable my account' %></p>
<% end %>

app/views/settings/disable_account_confirmation.erb
<h1>Disable your account</h1>
<%= form_tag({}, {name: 'disable_account_confirm'}) do %>
  <p>Confirmation code</p>
  <% if flash[:alert] %>
    <p class="alert"><%= flash[:alert] %></p>
  <% end %>
  <p><%= text_field_tag 'settings[confirmation_code]', nil, placeholder: "Enter your confirmation code" %></p>
  <p><%= submit_tag 'disable my account' %></p>
<% end %>

app/views/settings/disable_account_confirmed.erb
<h1>Your account have been disabled</h1>

<p>You have done to cry to mini-me!</p>
<p>You can always take out him from his deep sadness re-enabling your account.</p>

app/views/settings/edit.html.erb
<h1>Editing Setting</h1>

<%= render 'form' %>

app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Settings</h1>

<table>
  <thead>
    <tr>
      <th>Confirmation code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.confirmation_code %></td>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Confirmation code:</strong>
  <%= @setting.confirmation_code %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>