config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  get 'about' => 'about#index'
  get 'policies/terms_of_service'
  get 'policies/privacy'
  get 'policies/cookies' => 'policies#cookies_terms'
  get 'support/faq' => 'support#faq'
  get 'support/rules' => 'support#rules'
  get 'support/contact' => 'support#contact'
  post 'support/contact' => 'support#contact'
  get 'press' => 'press#index'

  get 'login' => 'users#login'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#delete'

  get 'signup' => 'users#new'
  get 'confirm_account' => 'users#confirm_account'
  post 'confirm_account' => 'users#validate_confirm_account'

  get 'recovery_password' => 'recovery_password#index'
  match 'recovery_password/confirm_code' => 'recovery_password#confirm_code', via: [:get, :post]
  match 'recovery_password/confirm_new_password' => 'recovery_password#confirm_new_password', via: [:get, :post]
  post 'recovery_password/set_new_password' => 'recovery_password#set_new_password'

  resources :users

  patch 'products/:id/disable' => 'products#disable', as: :disable_product
  patch 'products/:id/enable' => 'products#enable', as: :enable_product
  resources :products

  match 'cart' => 'cart#index', via: [:get, :post]
  post '/cart/add' => 'cart#add'

  get 'settings', to: 'settings#edit', as: :settings
  get 'settings', to: 'settings#edit', as: :setting
  get 'settings', to: 'settings#update'
  get 'settings/show', to: 'settings#show'
  get 'settings/disable_account' => 'settings#disable_account'
  match 'settings/disable_account/confirmation' => 'settings#disable_account_confirmation', via: [:get, :post], as: 'settings_disable_account_confirmation'
  get 'settings/disable_account/confirmed' => 'settings#disable_account_confirmed'

end

app/models/product.rb
class Product < ActiveRecord::Base
    validates :price,
      numericality: {
        greater_than_or_equal_to: 0,
        less_than_or_equal_to: 999999.99,
        message: 'Price must be a number between 0 - 999999.99'
      }

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :disable, :enable]
  before_action :check_administrator_privilege, only: [:create, :update, :disable, :enable]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    if uploaded_picture?
      uploaded_picture = params.require(:product)[:uploaded_picture]
      move_uploaded_pictured_into_default_path uploaded_picture
      @product.image_url = '/images/products/' + uploaded_picture.original_filename
    end


    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    if uploaded_picture?
      uploaded_picture = params.require(:product)[:uploaded_picture]
      move_uploaded_pictured_into_default_path uploaded_picture
      @product.image_url = '/images/products/' + uploaded_picture.original_filename
    end
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    respond_to do |format|
      format.html { render_404 }
      format.json { head :no_content }
    end
  end

  # PATCH /products/
  def disable
    @product.disabled_at = DateTime.now
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully disable.' }
        format.json { head :no_content }
      else
        format.html { redirect_to @product, notice: 'Product was not successfully disable.' }
        format.json { head :no_content }
      end
    end
  end

  # PATCH /products/
  def enable
    @product.disabled_at = nil
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully enable.' }
        format.json { head :no_content }
      else
        format.html { redirect_to @product, notice: 'Product was not successfully enable.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :id)
    end

    def uploaded_picture?
      params.required(:product).has_key?(:uploaded_picture)
    end

    def move_uploaded_pictured_into_default_path uploaded_picture
      File.open(
        Rails.root.join('public', 'images', 'products', uploaded_picture.original_filename),
        'wb'
      ) do |file|
        file.write(uploaded_picture.read)
      end
    end

    def check_administrator_privilege
        if ! (is_user_logged? && is_user_administrator?)
          redirect_to products_path, notice: 'You have not permissions for this operation'
        end
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product, html: {multipart: true}) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div>
    <%= f.label :image_url %><br>
    <%
    if @product.image_url.nil?
      concat image_tag 'products/default_image_url.png'
    else
      concat image_tag @product.image_url
    end
    %>
    <br>
    Upload picture: <%= f.file_field("uploaded_picture") %>    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <%
            if product.image_url.nil?
              concat image_tag 'products/default_image_url.png'
            else
              concat image_tag product.image_url
            end
          %>
        </td>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <% if product.disabled_at.nil? %>
          <td><%= link_to 'Disable', disable_product_path(product), method: :patch, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <td><%= link_to 'Enable', enable_product_path(product), method: :patch, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<%
  if @product.image_url.nil?
    concat image_tag 'products/default_image_url.png'
  else
    concat image_tag @product.image_url
  end
%>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<p>
  <strong>disabled:</strong>
  <%= @product.disabled_at %>
</p>
<%= form_tag(cart_path, {name: 'add_to_cart'}) do %>

  <input type="hidden" name="product_id" value="<%= @product.id %>">
  <input type="number" name="amount" size="2" min="1" placeholder="0" required/>
  <input type="submit" name="add_to_cart" value="add to cart" />
<% end  %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>