config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  get 'about' => 'about#index'
  get 'policies/terms_of_service'
  get 'policies/privacy'
  get 'policies/cookies' => 'policies#cookies_terms'
  get 'support/faq' => 'support#faq'
  get 'support/rules' => 'support#rules'
  get 'support/contact' => 'support#contact'
  post 'support/contact' => 'support#contact'
  get 'press' => 'press#index'

  get 'login' => 'users#login'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#delete'

  get 'signup' => 'users#new'
  get 'confirm_account' => 'users#confirm_account'
  post 'confirm_account' => 'users#validate_confirm_account'

  get 'recovery_password' => 'recovery_password#index'
  match 'recovery_password/confirm_code' => 'recovery_password#confirm_code', via: [:get, :post]
  match 'recovery_password/confirm_new_password' => 'recovery_password#confirm_new_password', via: [:get, :post]
  post 'recovery_password/set_new_password' => 'recovery_password#set_new_password'

  resources :users

  patch 'products/:id/disable' => 'products#disable', as: :disable_product
  patch 'products/:id/enable' => 'products#enable', as: :enable_product
  resources :products

  match 'cart' => 'cart#index', via: [:get, :post]
  post '/cart/add' => 'cart#add'

  get 'settings', to: 'settings#edit', as: :settings
  get 'settings', to: 'settings#edit', as: :setting
  get 'settings', to: 'settings#update'
  get 'settings/show', to: 'settings#show'
  get 'settings/disable_account' => 'settings#disable_account'
  match 'settings/disable_account/confirmation' => 'settings#disable_account_confirmation', via: [:get, :post], as: 'settings_disable_account_confirmation'
  get 'settings/disable_account/confirmed' => 'settings#disable_account_confirmed'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleShopRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="toolbar">
    <ul>
      <li>
        <a href="/" class="index">index</a>
      </li>
      <% if session.has_key? :user %>
        <li><%= link_to session[:user][:username], user_path(session[:user][:id]), {class: 'username'} %></li>
        <li><%= link_to 'settings', settings_path %></li>
        <li><%= link_to 'logout', logout_path %></li>
      <% else %>
        <li><%= link_to 'sign up', signup_path %></li>
        <li><%= link_to 'login', login_path %></li>
      <% end %>
    </ul>
  </div>
  <div id="content">
    <%= yield %>
  </div>
  <div class="footer">
      <a href="/policies/privacy">privacy</a>
      - <a href="/policies/terms_of_service">terms of service</a>
      - <a href="/policies/cookies">cookies</a>
      - <a href="/about">about</a>
      - <a href="/press">press</a>
      - <a href="/support/rules">rules</a>
      - <a href="/support/faq">faq</a>
      - <a href="/support/contact">contact</a>
  </div>
</body>
</html>